apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-svc-v0-10-0-2
  name: zookeeper-svc-v0-10-0-2
  namespace: kafka
spec:
  type: NodePort
  ports:
    - name: zookeeper-port
      port: 2181
      nodePort: 32181
      targetPort: 2181
  selector:
    app: zookeeper-v0-10-0-2