apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper-v1-0-2
  name: zookeeper-v1-0-2
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-v1-0-2
  template:
    metadata:
      labels:
        app: zookeeper-v1-0-2
    spec:
      containers:
        - image: wurstmeister/zookeeper
          imagePullPolicy: IfNotPresent
          name: zookeeper
          ports:
            - containerPort: 2181